// App user management constants
 const MIN_PASSWORD_LENGTH = 12;
 const SALT_ROUNDS = 12;
 const PASSWORD_LOCKOUT_THRESHOLD = 5;
 const PASSWORD_LOCKOUT_DURATION_MINUTES = 15;
const DUMMY_HASH = '$2b$12$invalidhashXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';


 module.exports = {
   MIN_PASSWORD_LENGTH,
   SALT_ROUNDS,
   PASSWORD_LOCKOUT_THRESHOLD,
   PASSWORD_LOCKOUT_DURATION_MINUTES,
   DUMMY_HASH
 };